// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6y6fag0lh5s0wwadBjJ64tE57JRcQxug',
    appId: '1:147696545331:web:95e81d36ff00b901a83d46',
    messagingSenderId: '147696545331',
    projectId: 'evently-app-05',
    authDomain: 'evently-app-05.firebaseapp.com',
    storageBucket: 'evently-app-05.firebasestorage.app',
    measurementId: 'G-LXFTQ2YVHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0Z8N3HTZPJLW46DlePGsjj9hDCRvTcw',
    appId: '1:147696545331:android:84ef918b7bba14bba83d46',
    messagingSenderId: '147696545331',
    projectId: 'evently-app-05',
    storageBucket: 'evently-app-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC41mxWrN7VGwDPwF_6ycut8WLYXbC4ZYw',
    appId: '1:147696545331:ios:7daf5a33f8055cd3a83d46',
    messagingSenderId: '147696545331',
    projectId: 'evently-app-05',
    storageBucket: 'evently-app-05.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC41mxWrN7VGwDPwF_6ycut8WLYXbC4ZYw',
    appId: '1:147696545331:ios:7daf5a33f8055cd3a83d46',
    messagingSenderId: '147696545331',
    projectId: 'evently-app-05',
    storageBucket: 'evently-app-05.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6y6fag0lh5s0wwadBjJ64tE57JRcQxug',
    appId: '1:147696545331:web:b0ced49d6aaaec95a83d46',
    messagingSenderId: '147696545331',
    projectId: 'evently-app-05',
    authDomain: 'evently-app-05.firebaseapp.com',
    storageBucket: 'evently-app-05.firebasestorage.app',
    measurementId: 'G-2CJXL5R0PD',
  );
}
